# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:48:10+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class MakePdfPostRequest(BaseModel):
    html: Optional[str] = None
    key: str
    url: Optional[str] = None
